version: "3"
services:

  react:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "3001:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.react-http.entrypoints=web
      - traefik.http.routers.react-http.rule=Host(`localhost`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.react-https.entrypoints=secureweb
      - traefik.http.routers.react-https.rule=Host(`localhost`)
      - traefik.http.routers.react-https.tls=true
      - traefik.http.routers.react-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.react-http.middlewares=https-redirect
      - traefik.http.services.react.loadbalancer.server.port=3000
    networks:
      - getaway

networks:
  getaway:
    #    external: true
